wget https://github.com/patience111/TNet/releases/download/v1.0.0/tnet-aels_tall.h5
wget https://github.com/patience111/TNet/releases/download/v1.0.0/tnet-aess_tall.h5
wget https://github.com/patience111/TNet/releases/download/v1.0.0/tnet-tntypes-ls_tall.h5
wget https://github.com/patience111/TNet/releases/download/v1.0.0/tnet-tntypes-ss_tall.h5
wget https://github.com/patience111/TNet/releases/download/v1.0.0/tnet-host-ls_tall.h5
wget https://github.com/patience111/TNet/releases/download/v1.0.0/tnet-host-ss_tall.h5
wget https://github.com/patience111/TNet/releases/download/v1.0.0/tnet-env-ls_tall.h5
wget https://github.com/patience111/TNet/releases/download/v1.0.0/tnet-env-ss_tall.h5
wget https://github.com/patience111/TNet/releases/download/v1.0.0/tnet-argls_tall.h5
wget https://github.com/patience111/TNet/releases/download/v1.0.0/tnet-argss_tall.h5
